"""Measured-equivalence gate: the app's ONNX text embedder vs sentence-transformers.

The load-bearing guard for the semantic-search spine (issue #121). The app runs
``paraphrase-multilingual-MiniLM-L12-v2`` as a vendored ONNX graph and
reproduces the sentence-transformer contract (128-token truncation, special
tokens, attention-mask mean pool, L2 normalize) in numpy. A wrong tokenizer,
mask, pooling, or normalize would still return plausible unit vectors that rank
*badly* — cosine similarity between two of our own vectors would look fine while
retrieval quietly rots. So correctness is measured against an INDEPENDENT
reference, not reasoned about:

* **Per-vector equivalence** — for every fixture string, cosine between the
  ONNX vector and the committed sentence-transformers reference vector
  (``fixtures/text-embedding/references.json``, regenerated by
  ``tools/generate_text_embedding_references.py`` in a dev-only torch env)
  must be >= 0.9999. The fixtures span scripts/languages, an exact quote,
  whitespace/punctuation, a 300-word monologue (128-token truncation), and a
  single unbroken long token — every drift site.
* **Retrieval-order agreement** — using each fixture as a query, the ranking of
  the others by cosine must be IDENTICAL under the ONNX and reference vectors.
  Catches drift that per-vector cosine tolerance could absorb but that would
  reorder results.
* **Batch/singleton agreement** — a string embedded inside a padded batch and
  on its own must produce the same vector (padding must not leak through the
  mask into the pooled result).

Prerequisites (each missing one is a SKIP in dev runs, a hard FAIL under
``VOXINT_PARITY_REQUIRED=1`` so a fully-skipped suite can never green-board a
release): the vendored weights at ``vendor/minilm/`` (or wherever
``VOXINT_MINILM_ONNX_PATH`` / ``VOXINT_MINILM_TOKENIZER_PATH`` point) and the
committed fixtures + references.
"""

from __future__ import annotations

import json
import os
from pathlib import Path

import numpy as np
import pytest

REPO = Path(__file__).resolve().parents[2]
FIXTURES_DIR = REPO / "tests" / "parity" / "fixtures" / "text-embedding"
FIXTURES_JSON = FIXTURES_DIR / "fixtures.json"
REFERENCES_JSON = FIXTURES_DIR / "references.json"
ONNX_PATH = Path(
    os.getenv("VOXINT_MINILM_ONNX_PATH") or (REPO / "vendor" / "minilm" / "model.onnx")
)
TOKENIZER_PATH = Path(
    os.getenv("VOXINT_MINILM_TOKENIZER_PATH")
    or (REPO / "vendor" / "minilm" / "tokenizer.json")
)

# Measured: the ONNX-vs-sentence-transformers cosine is 1.0000000 to 7 places on
# every fixture (amd64, ORT 1.28.0 CPU EP). The floor carries margin for BLAS/
# SIMD variance across hosts; loosening it is a space-id decision, not a fix.
COSINE_FLOOR = 0.9999

_REQUIRED = os.getenv("VOXINT_PARITY_REQUIRED") == "1"
_PREREQS = [
    (FIXTURES_JSON.exists(), f"{FIXTURES_JSON} missing"),
    (REFERENCES_JSON.exists(), f"{REFERENCES_JSON} missing"),
    (ONNX_PATH.exists(), f"{ONNX_PATH} missing — fetch the minilm-onnx-v1 asset"),
    (TOKENIZER_PATH.exists(), f"{TOKENIZER_PATH} missing — fetch the minilm-onnx-v1 asset"),
]

if _REQUIRED:
    _missing = [reason for ok, reason in _PREREQS if not ok]
    if _missing:
        pytest.fail(f"VOXINT_PARITY_REQUIRED=1 but prerequisites missing: {_missing}")
    import onnxruntime  # noqa: F401
    import tokenizers  # noqa: F401

    pytestmark: list[pytest.MarkDecorator] = []
else:
    pytest.importorskip("onnxruntime", reason="embeddings deps not installed")
    pytest.importorskip("tokenizers", reason="embeddings deps not installed")
    pytestmark = [pytest.mark.skipif(not ok, reason=reason) for ok, reason in _PREREQS]


def _cosine(a: np.ndarray, b: np.ndarray) -> float:
    return float(np.dot(a, b) / (np.linalg.norm(a) * np.linalg.norm(b)))


@pytest.fixture(scope="module")
def fixtures() -> list[dict[str, str]]:
    items: list[dict[str, str]] = json.loads(FIXTURES_JSON.read_text(encoding="utf-8"))[
        "items"
    ]
    ids = [item["id"] for item in items]
    assert len(set(ids)) == len(ids), "duplicate fixture ids"
    return items


@pytest.fixture(scope="module")
def references() -> dict[str, np.ndarray]:
    ref = json.loads(REFERENCES_JSON.read_text(encoding="utf-8"))
    assert ref["embedding_space"], "reference file missing embedding_space"
    return {k: np.asarray(v, dtype=np.float64) for k, v in ref["vectors"].items()}


@pytest.fixture(scope="module")
def onnx_vectors(fixtures: list[dict[str, str]]) -> dict[str, np.ndarray]:
    from voxint.embeddings.onnx_embedder import TextEmbedder

    embedder = TextEmbedder(str(ONNX_PATH), str(TOKENIZER_PATH))
    matrix = embedder.embed_texts([item["text"] for item in fixtures])
    return {item["id"]: matrix[i].astype(np.float64) for i, item in enumerate(fixtures)}


def test_reference_space_matches_embedder() -> None:
    from voxint.embeddings.onnx_embedder import EMBEDDING_SPACE

    ref = json.loads(REFERENCES_JSON.read_text(encoding="utf-8"))
    assert ref["embedding_space"] == EMBEDDING_SPACE, (
        "reference vectors were generated for a different embedding_space; "
        "regenerate with tools/generate_text_embedding_references.py"
    )


def test_per_vector_equivalence(
    fixtures: list[dict[str, str]],
    onnx_vectors: dict[str, np.ndarray],
    references: dict[str, np.ndarray],
) -> None:
    worst = 1.0
    worst_id = ""
    for item in fixtures:
        fid = item["id"]
        assert fid in references, f"no reference vector for {fid!r}"
        cos = _cosine(onnx_vectors[fid], references[fid])
        if cos < worst:
            worst, worst_id = cos, fid
    assert worst >= COSINE_FLOOR, (
        f"ONNX vs sentence-transformers cosine {worst:.7f} < {COSINE_FLOOR} "
        f"on fixture {worst_id!r} — the ONNX embedding path has drifted from the "
        "reference (tokenizer / mask / pooling / normalize)."
    )


def test_onnx_vectors_are_unit_norm(onnx_vectors: dict[str, np.ndarray]) -> None:
    for fid, vec in onnx_vectors.items():
        assert np.isclose(np.linalg.norm(vec), 1.0, atol=1e-5), f"{fid} not unit-norm"


def test_retrieval_order_agreement(
    fixtures: list[dict[str, str]],
    onnx_vectors: dict[str, np.ndarray],
    references: dict[str, np.ndarray],
) -> None:
    ids = [item["id"] for item in fixtures]
    for query in ids:
        others = [i for i in ids if i != query]
        onnx_rank = sorted(others, key=lambda i: -_cosine(onnx_vectors[query], onnx_vectors[i]))
        ref_rank = sorted(others, key=lambda i: -_cosine(references[query], references[i]))
        assert onnx_rank == ref_rank, (
            f"retrieval order disagrees for query {query!r}:\n"
            f"  onnx: {onnx_rank}\n  ref:  {ref_rank}"
        )


def test_batch_and_singleton_agree(fixtures: list[dict[str, str]]) -> None:
    from voxint.embeddings.onnx_embedder import TextEmbedder

    embedder = TextEmbedder(str(ONNX_PATH), str(TOKENIZER_PATH))
    texts = [item["text"] for item in fixtures]
    batched = embedder.embed_texts(texts)
    for i, text in enumerate(texts):
        single = embedder.embed_texts([text])[0]
        cos = _cosine(batched[i].astype(np.float64), single.astype(np.float64))
        assert cos >= 1.0 - 1e-6, (
            f"batch vs singleton mismatch for fixture {i} (cosine {cos:.7f}) — "
            "padding is leaking through the attention mask into the pooled vector."
        )
