"""3-level measured-equivalence gate: TitaNet ONNX engine vs the CUDA reference.

This is the parity harness that decides whether ``titanet-large-v1`` survives
onto non-NVIDIA backends (plan decision #3; policy in docs/gpu-contracts.md):

* **Mel level** — ``services/titanet/app/mel.py`` output vs the NeMo
  ``AudioToMelSpectrogramPreprocessor`` on identical post-preprocess audio
  (``references/mel/``, generated by ``tools/generate_mel_references.py``).
  Isolates the reimplemented front-end from preprocess-dependency skew.
* **Vector level** — the full ONNX engine chain on the golden corpus vs the
  committed CUDA service references (``references/cuda/embed.json``):
  identical ``skip_reason`` per window, ``snr_db`` within ±0.5 dB, per-window
  cosine ≥ the ratcheted floor.
* **Decision level** — replay the labeled same/different-speaker pairs
  (``corpus/embed-pairs.json``) through voxint's actual matching gates
  (``match_min_cosine`` 0.60 / ``grounded_min_cosine`` 0.70): no pair may
  cross either gate differently than the CUDA embeddings; pair-cosine drift
  and top-1/top-2 structure must stay inside the ratcheted bounds.

Tolerances were MEASURED first (2026-08-13, maintainer amd64 workstation, onnxruntime CPU EP on
amd64) and then ratcheted with margin — see docs/gpu-contracts.md for the
recorded numbers. Loosening any of them is a space-id decision, not a test fix.

Prerequisites (each missing one is an explicit SKIP in dev runs):
``uv sync --extra parity``; the exported graph at
``services/titanet/models/titanet-large.onnx`` (tools/export_titanet_onnx.py);
the committed mel/CUDA references. Release/CI runs set
``VOXINT_PARITY_REQUIRED=1``, which turns any missing prerequisite into a
hard failure so a fully-skipped suite can never green-board a release.
"""

from __future__ import annotations

import hashlib
import json
import os
from pathlib import Path
from typing import Any

import numpy as np
import pytest

from tests.contracts.conftest import service_package

REPO = Path(__file__).resolve().parents[2]
CORPUS_DIR = REPO / "tests" / "parity" / "fixtures" / "corpus"
MEL_DIR = REPO / "tests" / "parity" / "fixtures" / "references" / "mel"
CUDA_EMBED_JSON = REPO / "tests" / "parity" / "fixtures" / "references" / "cuda" / "embed.json"
ONNX_PATH = REPO / "services" / "titanet" / "models" / "titanet-large.onnx"
ONNX_PROVENANCE = REPO / "tests" / "parity" / "fixtures" / "onnx" / "provenance.json"

# --- Ratcheted tolerances. Measured 2026-08-13 (maintainer amd64 workstation, ORT CPU EP,
# --- vs the 0.3.0 CUDA references; recorded in docs/gpu-contracts.md):
# --- mel worst 2.2e-4 · vector cosine min 0.9999966 / p50 0.9999993 ·
# --- snr diff 0.0 · pair drift max 4.6e-4 · gate crossings 0 · top1 flips 0 ·
# --- margin drift max 3.5e-4. Bounds below carry ~5-100x margin for arm64
# --- SIMD/BLAS variance (arm64 to be measured when Phase 2 CI lands).
MEL_MAX_ABS_DIFF = 1e-3  # normalized log-mel units (measured worst 2.2e-4)
VECTOR_MIN_COSINE = 0.9995  # per embedded window (measured min 0.9999966)
SNR_TOLERANCE_DB = 0.5  # measured: exact agreement
PAIR_COSINE_MAX_DRIFT = 2e-3  # per labeled pair (measured max 4.6e-4)
TOP1_MARGIN_MAX_DRIFT = 2e-3  # (measured max 3.5e-4)
MATCHING_GATES = (0.60, 0.70)  # match_min_cosine / grounded_min_cosine

# Release/CI gate mode: with VOXINT_PARITY_REQUIRED=1 every missing
# prerequisite is a hard FAILURE, never a skip — a green board must mean the
# gate actually ran (a fully-skipped parity suite still exits 0 otherwise).
_REQUIRED = os.getenv("VOXINT_PARITY_REQUIRED") == "1"

_PREREQS = [
    (ONNX_PATH.exists(), f"{ONNX_PATH} missing — run tools/export_titanet_onnx.py"),
    (
        (MEL_DIR / "mel-references.npz").exists(),
        "mel references missing — run tools/generate_mel_references.py",
    ),
    (CUDA_EMBED_JSON.exists(), "CUDA embed references missing"),
    (ONNX_PROVENANCE.exists(), "ONNX export provenance missing"),
]
if _REQUIRED:
    _missing = [reason for ok, reason in _PREREQS if not ok]
    if _missing:
        pytest.fail(f"VOXINT_PARITY_REQUIRED=1 but prerequisites missing: {_missing}")
    import noisereduce  # noqa: F401
    import onnxruntime

    pytestmark: list[pytest.MarkDecorator] = []
else:
    onnxruntime = pytest.importorskip("onnxruntime", reason="parity extra not installed")
    pytest.importorskip("noisereduce", reason="parity extra not installed")
    pytestmark = [pytest.mark.skipif(not ok, reason=reason) for ok, reason in _PREREQS]


def _sha256(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def _cosine(a: np.ndarray, b: np.ndarray) -> float:
    return float(np.dot(a, b) / (np.linalg.norm(a) * np.linalg.norm(b)))


@pytest.fixture(scope="session")
def corpus_windows() -> list[dict[str, Any]]:
    windows = json.loads((CORPUS_DIR / "embed-windows.json").read_text())["windows"]
    # Duplicate ids would silently shrink coverage (later dicts keyed by id
    # collapse) — a malformed corpus must fail loudly, not thin the gate.
    ids = [w["id"] for w in windows]
    assert len(set(ids)) == len(ids), "duplicate window ids in embed-windows.json"
    return windows


@pytest.fixture(scope="session")
def cuda_reference() -> dict[str, Any]:
    ref = json.loads(CUDA_EMBED_JSON.read_text())
    # The reference must describe the exact corpus we are about to embed —
    # audio AND the window/pair definitions (editing embed-pairs.json could
    # otherwise silently weaken the decision-level gate).
    for name in ("embed-corpus.wav", "embed-windows.json", "embed-pairs.json"):
        actual = _sha256(CORPUS_DIR / name)
        bound = ref["meta"]["corpus_files_sha256"][name]
        assert actual == bound, f"{name} does not match the committed CUDA reference"
    assert ref["embedding_space"] == "titanet-large-v1"
    return ref


def test_onnx_artifact_matches_committed_provenance() -> None:
    """The graph under test must be the exact artifact the recorded PASS
    verdict certifies — a stale/corrupt/re-exported .onnx must fail loudly,
    not ride a green gate."""
    prov = json.loads(ONNX_PROVENANCE.read_text())
    actual = _sha256(ONNX_PATH)
    assert actual == prov["onnx_sha256"], (
        f"local .onnx sha256 {actual} differs from committed provenance "
        f"{prov['onnx_sha256']} — re-export with tools/export_titanet_onnx.py "
        "and commit the updated provenance.json alongside a fresh gate run"
    )
    assert prov["graph_inputs"] == ["audio_signal", "length"]
    assert "embs" in prov["graph_outputs"]
    assert prov["mel_frontend_in_graph"] is False


@pytest.fixture(scope="session")
def onnx_outcomes(corpus_windows: list[dict[str, Any]]) -> dict[str, Any]:
    """Run the real ONNX engine (same code path as the service) on the full
    corpus once; every vector/decision test reads from this.

    ``VOXINT_PARITY_ORT_PROVIDERS`` threads straight into the engine's
    ``TITANET_ORT_PROVIDERS`` so the FULL 3-level gate can be run against the
    CUDA references under an alternative EP (e.g. CoreML on Apple Silicon:
    ``VOXINT_PARITY_ORT_PROVIDERS=CoreMLExecutionProvider``). Unset, the gate
    measures the shipped default (CPU EP) exactly as before.
    """
    saved_env = {
        k: os.environ.get(k)
        for k in ("TITANET_ONNX_PATH", "EMBED_ENGINE", "TITANET_ORT_PROVIDERS")
    }
    os.environ["TITANET_ONNX_PATH"] = str(ONNX_PATH)
    os.environ["EMBED_ENGINE"] = "onnx"
    parity_providers = os.getenv("VOXINT_PARITY_ORT_PROVIDERS")
    if parity_providers:
        os.environ["TITANET_ORT_PROVIDERS"] = parity_providers
    else:
        # The DEFAULT lane must measure the CPU EP: an ambient
        # TITANET_ORT_PROVIDERS (e.g. a maintainer dogfooding CoreML) would
        # otherwise be measured while the verdict records "default".
        os.environ.pop("TITANET_ORT_PROVIDERS", None)
    try:
        with service_package("titanet"):
            from app.embedding import create_embedder

            embedder = create_embedder()
            embedder.load_model()
            windows = [(w["start_seconds"], w["end_seconds"]) for w in corpus_windows]
            outcomes = embedder.embed_windows(str(CORPUS_DIR / "embed-corpus.wav"), windows)
    finally:
        for key, value in saved_env.items():
            if value is None:
                os.environ.pop(key, None)
            else:
                os.environ[key] = value
    assert embedder.engine == "onnxruntime"
    return {
        "engine": embedder.engine,
        "engine_version": embedder.engine_version,
        # After the TITANET_ORT_PROVIDERS change this reflects the primary EP
        # ("cpu", "metal" for CoreML, ...) — recorded so a verdict report can
        # never misattribute which provider the gate actually measured.
        "device": embedder.device_name,
        "requested_providers": parity_providers or "(default: CPUExecutionProvider)",
        "by_id": {w["id"]: outcome for w, outcome in zip(corpus_windows, outcomes, strict=True)},
    }


class TestMelLevel:
    def test_mel_frontend_matches_nemo_preprocessor(self) -> None:
        refs = np.load(MEL_DIR / "mel-references.npz")
        meta = json.loads((MEL_DIR / "mel-references.json").read_text())
        # The mel references must have been generated from this exact corpus.
        for name, bound in meta["corpus_files_sha256"].items():
            assert _sha256(CORPUS_DIR / name) == bound, (
                f"mel references were generated from a different {name}"
            )
        with service_package("titanet"):
            from app.mel import mel_spectrogram

        worst = 0.0
        per_window: dict[str, float] = {}
        for entry in meta["windows"]:
            wid = str(entry["id"])
            audio = refs[f"audio_{wid}"]
            expected = refs[f"mel_{wid}"]
            valid = int(entry["mel_valid_frames"])
            ours = mel_spectrogram(audio)
            # The NeMo reference is padded to pad_to=16; our front-end emits
            # exactly the valid frames (the exported graph has no conv
            # masking) — compare on the valid region.
            assert ours.shape == (expected.shape[0], valid), (
                f"{wid}: shape {ours.shape} vs valid {(expected.shape[0], valid)}"
            )
            diff = float(np.max(np.abs(ours - expected[:, :valid])))
            per_window[wid] = diff
            worst = max(worst, diff)
        rounded = {k: round(v, 8) for k, v in per_window.items()}
        print(f"\nmel-level max abs diff per window: {rounded}")
        print(f"mel-level worst-case: {worst:.3e} (gate {MEL_MAX_ABS_DIFF:.0e})")
        assert worst <= MEL_MAX_ABS_DIFF


class TestVectorLevel:
    def test_skip_reasons_and_snr_identical(
        self, onnx_outcomes: dict[str, Any], cuda_reference: dict[str, Any]
    ) -> None:
        for ref in cuda_reference["windows"]:
            outcome = onnx_outcomes["by_id"][ref["id"]]
            assert outcome.skip_reason == ref["skip_reason"], (
                f"{ref['id']}: skip_reason {outcome.skip_reason!r} vs CUDA {ref['skip_reason']!r}"
            )
            if ref["snr_db"] is not None:
                assert outcome.snr_db == pytest.approx(ref["snr_db"], abs=SNR_TOLERANCE_DB), (
                    f"{ref['id']}: snr_db {outcome.snr_db} vs CUDA {ref['snr_db']}"
                )

    def test_embedded_window_cosines(
        self, onnx_outcomes: dict[str, Any], cuda_reference: dict[str, Any]
    ) -> None:
        cosines: dict[str, float] = {}
        for ref in cuda_reference["windows"]:
            if ref["embedding"] is None:
                continue
            outcome = onnx_outcomes["by_id"][ref["id"]]
            assert outcome.embedding is not None, f"{ref['id']}: ONNX skipped, CUDA embedded"
            cosines[ref["id"]] = _cosine(np.array(outcome.embedding), np.array(ref["embedding"]))
        values = np.array(sorted(cosines.values()))
        print(
            f"\nvector-level cosines over {len(values)} windows: "
            f"min={values[0]:.6f} p1={np.percentile(values, 1):.6f} "
            f"p50={np.percentile(values, 50):.6f} max={values[-1]:.6f}"
        )
        worst_ids = sorted(cosines, key=lambda k: cosines[k])[:5]
        print(f"worst windows: {[(w, round(cosines[w], 6)) for w in worst_ids]}")
        assert float(values[0]) >= VECTOR_MIN_COSINE


class TestDecisionLevel:
    @pytest.fixture(scope="class")
    def pair_cosines(
        self, onnx_outcomes: dict[str, Any], cuda_reference: dict[str, Any]
    ) -> dict[str, Any]:
        pairs = json.loads((CORPUS_DIR / "embed-pairs.json").read_text())
        cuda_by_id = {
            w["id"]: np.array(w["embedding"])
            for w in cuda_reference["windows"]
            if w["embedding"] is not None
        }
        onnx_by_id = {
            wid: np.array(o.embedding)
            for wid, o in onnx_outcomes["by_id"].items()
            if o.embedding is not None
        }
        rows = []
        for kind in ("same_speaker_pairs", "different_speaker_pairs"):
            for a, b in pairs[kind]:
                if a not in cuda_by_id or b not in cuda_by_id:
                    continue  # skipped windows can't pair
                rows.append(
                    {
                        "pair": (a, b),
                        "kind": kind,
                        "cuda": _cosine(cuda_by_id[a], cuda_by_id[b]),
                        "onnx": _cosine(onnx_by_id[a], onnx_by_id[b]),
                    }
                )
        assert rows, "no evaluable pairs"
        return {"rows": rows, "cuda_by_id": cuda_by_id, "onnx_by_id": onnx_by_id}

    def test_no_gate_crossings(self, pair_cosines: dict[str, Any]) -> None:
        crossings = [
            (r["pair"], r["kind"], gate, r["cuda"], r["onnx"])
            for r in pair_cosines["rows"]
            for gate in MATCHING_GATES
            if (r["cuda"] >= gate) != (r["onnx"] >= gate)
        ]
        drifts = np.array([abs(r["onnx"] - r["cuda"]) for r in pair_cosines["rows"]])
        print(
            f"\ndecision-level pair drift over {len(drifts)} pairs: "
            f"p50={np.percentile(drifts, 50):.2e} p99={np.percentile(drifts, 99):.2e} "
            f"max={drifts.max():.2e}"
        )
        assert not crossings, f"gate crossings: {crossings[:10]}"
        assert float(drifts.max()) <= PAIR_COSINE_MAX_DRIFT

    def test_top1_top2_structure_stable(self, pair_cosines: dict[str, Any]) -> None:
        """Roster-rank stability: for every embedded window, the most-similar
        other window must not change, and the top-1/top-2 margin must not move
        by more than the ratcheted bound."""
        cuda_by_id = pair_cosines["cuda_by_id"]
        onnx_by_id = pair_cosines["onnx_by_id"]
        ids = sorted(cuda_by_id)
        cuda_mat = np.stack([cuda_by_id[i] for i in ids])
        onnx_mat = np.stack([onnx_by_id[i] for i in ids])

        def sim_matrix(mat: np.ndarray) -> np.ndarray:
            normed = mat / np.linalg.norm(mat, axis=1, keepdims=True)
            sims = normed @ normed.T
            np.fill_diagonal(sims, -np.inf)
            return sims

        cuda_sims = sim_matrix(cuda_mat)
        onnx_sims = sim_matrix(onnx_mat)
        top1_changes = []
        margin_drifts = []
        for row, wid in enumerate(ids):
            cuda_order = np.argsort(cuda_sims[row])[::-1]
            onnx_order = np.argsort(onnx_sims[row])[::-1]
            if cuda_order[0] != onnx_order[0]:
                # Every flip is recorded and gated (strictly, even degenerate
                # near-ties); the CUDA margin is captured for failure analysis.
                cuda_margin = cuda_sims[row][cuda_order[0]] - cuda_sims[row][cuda_order[1]]
                top1_changes.append((wid, ids[cuda_order[0]], ids[onnx_order[0]], cuda_margin))
            cuda_margin = cuda_sims[row][cuda_order[0]] - cuda_sims[row][cuda_order[1]]
            onnx_margin = onnx_sims[row][onnx_order[0]] - onnx_sims[row][onnx_order[1]]
            margin_drifts.append(abs(cuda_margin - onnx_margin))
        drifts = np.array(margin_drifts)
        print(
            f"\ntop1 changes: {len(top1_changes)}; margin drift "
            f"p50={np.percentile(drifts, 50):.2e} max={drifts.max():.2e}"
        )
        if top1_changes:
            print(f"top1 flips (window, cuda_top1, onnx_top1, cuda_margin): {top1_changes[:10]}")
        assert not top1_changes
        assert float(drifts.max()) <= TOP1_MARGIN_MAX_DRIFT


class TestRepeatDeterminism:
    """Same-window repeat through ONE engine session.

    The shipped CPU EP is deterministic — a repeat must be bitwise identical,
    and any drift is an engine-stack regression. Alternative EPs threaded in
    via ``VOXINT_PARITY_ORT_PROVIDERS`` (CoreML on Apple Silicon) may not be:
    the probe prints the measured drift for the per-chip verdict report and
    holds a pre-registered smoke bound (cosine ≥ 0.99999) that a ratcheting
    pass tightens once real numbers exist.
    """

    def test_same_window_repeat_is_stable(
        self, corpus_windows: list[dict[str, Any]]
    ) -> None:
        window = next(
            w for w in corpus_windows if w["expected_skip_reason"] is None
        )
        saved_env = {
            k: os.environ.get(k)
            for k in ("TITANET_ONNX_PATH", "EMBED_ENGINE", "TITANET_ORT_PROVIDERS")
        }
        os.environ["TITANET_ONNX_PATH"] = str(ONNX_PATH)
        os.environ["EMBED_ENGINE"] = "onnx"
        parity_providers = os.getenv("VOXINT_PARITY_ORT_PROVIDERS")
        if parity_providers:
            os.environ["TITANET_ORT_PROVIDERS"] = parity_providers
        else:
            # The DEFAULT lane must measure the CPU EP: an ambient
            # TITANET_ORT_PROVIDERS (e.g. a maintainer dogfooding CoreML) would
            # otherwise be measured while the verdict records "default".
            os.environ.pop("TITANET_ORT_PROVIDERS", None)
        try:
            with service_package("titanet"):
                from app.embedding import create_embedder

                embedder = create_embedder()
                embedder.load_model()
                bounds = [(window["start_seconds"], window["end_seconds"])] * 2
                outcomes = embedder.embed_windows(
                    str(CORPUS_DIR / "embed-corpus.wav"), bounds
                )
        finally:
            for key, value in saved_env.items():
                if value is None:
                    os.environ.pop(key, None)
                else:
                    os.environ[key] = value
        first = np.asarray(outcomes[0].embedding, dtype=np.float64)
        second = np.asarray(outcomes[1].embedding, dtype=np.float64)
        max_abs = float(np.max(np.abs(first - second)))
        print(
            f"\nrepeat-determinism ({embedder.device_name}, "
            f"providers={parity_providers or 'default'}): max abs diff {max_abs:.3e}"
        )
        if parity_providers:
            assert _cosine(first, second) >= 0.99999, (
                f"repeat drift under {parity_providers}: cosine "
                f"{_cosine(first, second)} — record in the verdict report"
            )
        else:
            assert np.array_equal(first, second), (
                f"CPU EP repeat must be bitwise identical (max abs {max_abs:.3e})"
            )
