"""Ingest: the submission + requeue service shared by CLI and API.

Submit functions return a :class:`SubmissionResult` carrying the run id and a
``publish()`` method. The caller commits the session, then calls
``result.publish()`` (commit-before-publish). See :mod:`voxint.ingest.service`.
"""

from voxint.ingest.service import (
    EffectiveConfigPreview,
    IngestError,
    ItemTrashedError,
    MediaDeletePlan,
    MediaUnlinkResult,
    MissingStageError,
    OperationInProgressError,
    RestartImpact,
    RunArchivedError,
    RunMediaNotDeletableError,
    RunNotArchivableError,
    RunNotCancellableError,
    RunNotFailedError,
    RunNotFoundError,
    RunNotPausableError,
    RunNotPausedError,
    RunNotRestartableError,
    RunRestartBlockedError,
    RunRestartLabelRiskError,
    SubmissionResult,
    UploadConflictError,
    UploadTooLargeError,
    UploadValidationError,
    UrlValidationError,
    archive_run,
    cancel_run,
    delete_run_derived_media,
    pause_run,
    preview_effective_config,
    reconcile_orphaned_incoming,
    requeue_failed_run,
    restart_impact,
    restart_run,
    resume_run,
    submit_media_item,
    submit_media_item_if_new,
    submit_upload,
    submit_url,
    unarchive_run,
    unlink_media_paths,
    validate_ingest_url,
)
from voxint.pipeline.transitions import RunSnapshot

__all__ = [
    "EffectiveConfigPreview",
    "IngestError",
    "ItemTrashedError",
    "MediaDeletePlan",
    "MediaUnlinkResult",
    "MissingStageError",
    "OperationInProgressError",
    "RestartImpact",
    "RunArchivedError",
    "RunMediaNotDeletableError",
    "RunNotArchivableError",
    "RunNotCancellableError",
    "RunNotFailedError",
    "RunNotFoundError",
    "RunNotPausableError",
    "RunNotPausedError",
    "RunNotRestartableError",
    "RunRestartBlockedError",
    "RunRestartLabelRiskError",
    "RunSnapshot",
    "SubmissionResult",
    "UploadConflictError",
    "UploadTooLargeError",
    "UploadValidationError",
    "UrlValidationError",
    "archive_run",
    "cancel_run",
    "delete_run_derived_media",
    "pause_run",
    "preview_effective_config",
    "reconcile_orphaned_incoming",
    "requeue_failed_run",
    "restart_impact",
    "restart_run",
    "resume_run",
    "submit_media_item",
    "submit_media_item_if_new",
    "submit_upload",
    "submit_url",
    "unarchive_run",
    "unlink_media_paths",
    "validate_ingest_url",
]
