"""Pinned, verifiable facts about the whisper-bakeoff corpus sources.

Single source of truth shared by the acquisition tool
(``tools/prepare_bakeoff_corpus.py``) and the contract test
(``tests/contracts/test_bakeoff_corpus.py``). Kept as data (not buried in the
script) so the pins are reviewable and machine-checkable.

Provenance of these pins (obtained 2026-08-16 via a codex web-research pass;
they are the *expected* values a maintainer's first ``generate`` run confirms
against real bytes, and every later ``prepare`` run fails closed on):

  * TED-LIUM 3 — the official OpenSLR SLR51 tarball is gone (404) and the old
    ``LIUM/tedlium`` HF endpoint 401s. The lightweight, license-clean source is
    the two *legacy* Release-3 archives on ``kfajdsl/tedlium`` at a pinned
    commit: the original full-talk ``.sph`` + ``.stm`` pairs (~481 MB total, 19
    talks), no ``datasets``/``pyarrow`` needed. STM is segment-level only and
    carries ``ignore_time_segment_in_scoring`` masks. CC-BY-NC-ND-3.0 → metrics
    only, transcripts NEVER committed.
  * AMI IHM — individual headset WAVs plus the official manual NXT annotations
    v1.6.2 (word-aligned references). CC-BY-4.0 → gold + committed CT2 baseline
    are redistributable; audio still never committed (repo size).

Audio is never committed for either dataset; TED transcripts are never committed.
"""

from __future__ import annotations

from typing import Final

# Bump when the selection algorithm or its seed changes — recorded in the
# manifest so a reshuffle is a visible, deliberate event, not silent drift.
SELECTION_VERSION: Final = "bakeoff-select-v1"
SELECTION_SEED: Final = "voxint-whisper-bakeoff-33"

# Pre-registered strata targets (see docs/gpu-contracts.md). AMI/TED are fetched;
# the synthetic strata reference committed espeak-ng fixtures (generated by the
# existing corpus tooling, never downloaded).
STRATA_TARGETS: Final[dict[str, int]] = {
    "ami_ihm": 15,
    "tedlium3": 15,
    "synthetic_silence": 5,
    "synthetic_bait": 5,
    "synthetic_short_clean": 5,
}

# ts_granularity values and the boundary-drift eligibility rule (only
# word-aligned gold may be scored for segment/word boundary drift).
TS_GRANULARITIES: Final = ("word", "segment", "none")


def boundary_gate_eligible(ts_granularity: str) -> bool:
    """A file may enter the boundary-drift gate iff it has word-aligned gold."""
    return ts_granularity == "word"


# --- TED-LIUM 3 -----------------------------------------------------------
TEDLIUM3: Final = {
    "dataset": "tedlium3",
    "license_spdx": "CC-BY-NC-ND-3.0",
    "ts_granularity": "segment",
    "commit_transcripts": False,  # NC-ND: metrics only
    "hf_repo": "kfajdsl/tedlium",
    "hf_revision": "b3c6724dbeafb7b48425b3bf44c40ccf0b201b54",
    # https://huggingface.co/datasets/{repo}/resolve/{rev}/{path}
    "url_template": (
        "https://huggingface.co/datasets/kfajdsl/tedlium/resolve/"
        "b3c6724dbeafb7b48425b3bf44c40ccf0b201b54/{path}"
    ),
    "archives": {
        "TEDLIUM_release3/legacy/dev.tar.gz": {
            "size_bytes": 174796847,
            "sha256": "4333d359ec3a7271b1fae03acd22a49de7b6cf293835efeef4a0c4c04fa192d6",
        },
        "TEDLIUM_release3/legacy/test.tar.gz": {
            "size_bytes": 306583330,
            "sha256": "6be5e49a4dfc11ca4f4404acfefeadea3dda02f6d615342df4bb2e3cc37e530d",
        },
    },
}

# --- AMI IHM --------------------------------------------------------------
AMI: Final = {
    "dataset": "ami_ihm",
    "license_spdx": "CC-BY-4.0",
    "ts_granularity": "word",
    "commit_transcripts": True,  # CC-BY: gold + baseline redistributable
    "audio_url_template": (
        "https://groups.inf.ed.ac.uk/ami/AMICorpusMirror/amicorpus/"
        "{meeting}/audio/{meeting}.Headset-{channel}.wav"
    ),
    "annotations_url": (
        "https://groups.inf.ed.ac.uk/ami/AMICorpusAnnotations/"
        "ami_public_manual_1.6.2.zip"
    ),
    "annotations_sha256": (
        "b56e5babb2496b8795deeeda7e71178d7fbc9963f94276cf2a3f4b56ebbc9f9d"
    ),
    "annotations_version": "manual-1.6.2",
    # Members inside the annotations zip (str.format with meeting/agent):
    "words_member": "words/{meeting}.{agent}.words.xml",
    "segments_member": "segments/{meeting}.{agent}.segments.xml",
    "meetings_member": "corpusResources/meetings.xml",
    # Deterministic fixed-window policy for the multi-minute slices: a window of
    # WINDOW_S starting at OFFSET_S, taken only from recordings long enough to
    # hold it. Content-independent (preserves pre-registration); word gold is
    # extracted within the window at generate time.
    "slice_offset_s": 120.0,
    "slice_window_s": 240.0,
}
